import requests

resp = requests.get("http://spidsmus.sdma.nzcorp.net:9090/termite/toolkit/vocinfo.api")
a = resp.json()
keys_all = a.keys()
voc_groups = {
    "Animal health and nutrition": "ANIMALFEED,BIOAG",
    "Food and beverage": "FOODBEV,FOODSENSORY,MICRONUTRIENTS,FOODON",
    "Household care": "HOUSEHOLDTECH",
    "Technical industries": "TECH,LAB_EQUIPMENT,SPMF",
    "Human Health": "MDRAE,CONTEXT,BIOTHERA,ABTYPE,INDICATIONBOOST,MARKER,ANAT,NCIT",
    "Bioenergy and Biomass": "AGRIBIO,SAGR",
    "Biochemical": "BIOCHEM,BIOCHEMPLUS,METABOLITE",
    "Enzymes": "ENZYMES_NEW",
    "Genes and Molecular processes": "HGNCGENE,GOONTOL",
    "Taxonomy, all organisms": "TAXARC,TAXBAC,TAXEUM,TAXPLANT,TAXVIRUS,TAXBAC,TAXFUNG,TAXPLANT",
    "Plant terms": "PONT",
    "Companies, competitors, clients": "COMPANY,NZCOMP,NZCLIENTS",
}

vocabs_all = {
    "Antibodies (blood)": "ABTYPE",
    # "Negative conditions (health)":"ADVENT",
    "Age groups": "AGEGROUPE",
    "Agricultural science": "AGRIBIO",
    "Human Anatomy": "ANAT",
    "Animal feed terms": "ANIMALFEED",
    "Biological agriculture terms": "BIOAG",
    #   "Biochemistry":"BIOCHEM",
    "Biochemistry+": "BIOCHEMPLUS",
    "Biotherapeuticals": "BIOTHERA",
    "Bioogical verbs": "BIOVERB",
    "Time units": "CDISCAGEF",
    "Cell lines": "CELLLINE",
    "Cell types": "CELLTYP",
    "Clinical measurements": "CLINMES",
    "Clinical procedures": "CLINPROC",
    "Clinical terms": "CLINTAG",
    "Companies": "COMPANY",
    "Contextual terms": "CONTEXT",
    "Countries": "COUNTRY",
    "Date identifier": "DATE",
    "Drug names/formulas": "DRUG",
    "ELN numbers": "ELNNUMBERS",
    "Enzymes": "ENZYMES_NEW",
    "Ethnicity terms": "ETHNIC",
    "Food foam terms": "FOAM",
    #   "Food and beverages":"FOODANDBEV",
    "Food and beverages": "FOODBEV",
    "Food item/object terms": "FOODON",
    "Food sensory terms": "FOODSENSORY",
    #   "Genes":"GENE",
    #   "Genes+":"GENEBOOST",
    "Genes": "HGNCGENE",
    "Geographical terms": "GEO",
    "Genetic terms": "GOONTOL",
    "Household tech": "HOUSEHOLDTECH",
    "Human phenoptype": "HPO",
    "Human identification": "HUMANID",
    #   "Indications":"INDICATION",
    "Indications": "INDICATIONBOOST",
    "Institutes": "INSTITUTE",
    "Lab chemicals": "LABCHEM",
    "Lab equipment": "LAB_EQUIPMENT",
    "Luna numbers": "LUNANUMBERS",
    "Diagnosis indication": "MARKER",
    "Acute negative medical conditions": "MDRACUTEAE",
    "Negative medical conditions": "MDRAE",
    "Measurements": "MEASURE",
    "Metabolites": "METABOLITE",
    "Mouse strains": "MGISTRAINS",
    "Micronutrients": "MICRO",
    "Microbiome": "MICROBIOME",
    "Food micronutrients": "MICRONUTRIENTS",
    "Microbial species": "MICROSPECIES",
    "Mechanism of action": "MOA",
    "MyMS numbers": "MYMS",
    "Cancer diseases": "NCIT",
    "NN numbers": "NNNUMBERS",
    "Novozymes products": "NOVOPROD",
    "NullVocab": "NULL",
    "Novozymes clients": "NZCLIENTS",
    "Novozymes competitors": "NZCOMP",
    "OneHealth terms": "ONEHEALTH",
    "Patent numbers": "PATENTNUMBERS",
    "Plant terms": "PONT",
    "Project numbers": "PROJ_NO",
    "Research codes": "RESCODE",
    "Agrochemical terms": "SAGR",
    "Sequence numbers": "SEQNUMBERS",
    "Species": "SPECIES",
    "Pharmaceutical science": "SPMF",
    "Archeal taxonomy": "TAXARC",
    "Bacterial taxonomy": "TAXBAC",
    "Eukaryote taxonomy": "TAXEUM",
    "Fungal taxonomy": "TAXFUNG",
    "Plant taxonomy": "TAXPLANT",
    "Viral taxonomy": "TAXVIRUS",
    "Technology": "TECH",
}

# vocabs_all = {"Antibodies (blood)":"ABTYPE",
#                   "Negative conditions (health)":"ADVENT",
#                   "Age groups":"AGEGROUPE",
#                   "Agricultural science":"AGRIBIO",
#                   "Human Anatomy":"ANAT",
#                   "Animal feed terms":"ANIMALFEED",
#                   "Biological agriculture terms":"BIOAG",
#                   "Biochemistry":"BIOCHEM",
#                   "Biochemistry+":"BIOCHEMPLUS",
#                   "Biotherapeuticals":"BIOTHERA",
#                   "Bioogical verbs":"BIOVERB",
#                   "Time units":"CDISCAGEF",
#                   "Cell lines":"CELLLINE",
#                   "Cell types":"CELLTYP",
#                   "Clinical measurements":"CLINMES",
#                   "Clinical procedures":"CLINPROC",
#                   "Clinical terms":"CLINTAG",
#                   "Companies":"COMPANY",
#                   "Contextual terms":"CONTEXT",
#                   "Countries":"COUNTRY",
#                   "Date identifier":"DATE",
#                   "Drug names/formulas":"DRUG",
#                   "ELN numbers":"ELNNUMBERS",
#                   "Enzymes":"ENZYMES_NEW",
#                   "Ethnicity terms":"ETHNIC",
#                   "Food foam terms":"FOAM",
#                   "Food and beverages":"FOODANDBEV",
#                   "Food and beverages+":"FOODBEV",
#                   "Food item/object terms":"FOODON",
#                   "Food sensory terms":"FOODSENSORY",
#                   "Genes":"GENE",
#                   "Genes+":"GENEBOOST",
#                   "Genes++":"GENEBOOSTPLUS",
#                   "Geographical terms":"GEO",
#                   "Genetic terms":"GOONTOL",
#                   "Household tech":"HOUSEHOLDTECH",
#                   "Human phenoptype":"HPO",
#                   "Human identification":"HUMANID",
#                   "Indications":"INDICATION",
#                   "Indications+":"INDICATIONBOOST",
#                   "Institutes":"INSTITUTE",
#                   "Lab chemicals":"LABCHEM",
#                   "Lab equipment":"LAB_EQUIPMENT",
#                   "Luna numbers":"LUNANUMBERS",
#                   "Diagnosis indication":"MARKER",
#                   "Acute negative medical conditions":"MDRACUTEAE",
#                   "Negative medical conditions":"MDRAE",
#                   "Measurements":"MEASURE",
#                   "Metabolites":"METABOLITE",
#                   "Mouse strains":"MGISTRAINS",
#                   "Micronutrients":"MICRO",
#                   "Microbiome":"MICROBIOME",
#                   "Food micronutrients":"MICRONUTRIENTS",
#                   "Microbial species":"MICROSPECIES",
#                   "Mechanism of action":"MOA",
#                   "MyMS numbers":"MYMS",
#                   "Cancer diseases":"NCIT",
#                   "NN numbers":"NNNUMBERS",
#                   "Novozymes products":"NOVOPROD",
#                   "NullVocab":"NULL",
#                   "Novozymes clients":"NZCLIENTS",
#                   "Novozymes competitors":"NZCOMP",
#                   "OneHealth terms":"ONEHEALTH",
#                   "Patent numbers":"PATENTNUMBERS",
#                   "Plant terms":"PONT",
#                   "Project numbers":"PROJ_NO",
#                   "Research codes":"RESCODE",
#                   "Agrochemical terms":"SAGR",
#                   "Sequence numbers":"SEQNUMBERS",
#                   "Species":"SPECIES",
#                   "Pharmaceutical science":"SPMF",
#                   "Archeal taxonomy":"TAXARC",
#                   "Bacterial taxonomy":"TAXBAC",
#                   "Eukaryote taxonomy":"TAXEUM",
#                   "Fungal taxonomy":"TAXFUNG",
#                   "Plant taxonomy":"TAXPLANT",
#                   "Viral taxonomy":"TAXVIRUS",
#                   "Technology":"TECH"}
